async function initCheckout(){
 const inventory=await loadInventory().catch(()=>null),c=getCart(),box=document.getElementById('checkoutItems');
 if(!inventory||!c.length){box.innerHTML='<div class="empty-cart"><h2>IL CARRELLO È VUOTO.</h2><a class="text-link" href="shop.html">TORNA ALLO SHOP →</a></div>';document.querySelector('form')?.remove();return}
 const normalized=[]; const invalid=[];
 for(const item of c){const p=inventory.products.find(x=>x.id===item.id);const available=p?sizeStock(p,item.size):0;if(!p||available<item.qty)invalid.push(`${item.name} · taglia ${item.size}`);else normalized.push({...item,price:p.price,image:p.image})}
 if(invalid.length){box.innerHTML=`<div class="checkout-warning"><strong>CONTROLLA IL CARRELLO.</strong><p>La disponibilità è cambiata per: ${invalid.map(escapeHtml).join(', ')}.</p><a class="text-link" href="shop.html#cart">TORNA AL CARRELLO →</a></div>`;document.querySelector('form')?.remove();return}
 box.innerHTML=normalized.map(i=>`<article class="checkout-item"><img src="${escapeHtml(i.image)}" alt="${escapeHtml(i.brand)} ${escapeHtml(i.name)}" loading="lazy" onerror="this.src='assets/editorial-campaign.jpg'"><div><span>${escapeHtml(i.brand)}</span><strong>${escapeHtml(i.name)}</strong><small>Taglia ${escapeHtml(i.size)} · Quantità ${i.qty}</small></div><b>${money(i.price*i.qty)}</b></article>`).join('');
 const subtotal=normalized.reduce((s,i)=>s+i.price*i.qty,0),shipEl=document.getElementById('shipping'),totalEl=document.getElementById('checkoutTotal');document.getElementById('subtotal').textContent=money(subtotal);
 function refresh(){const d=document.querySelector('input[name=delivery]:checked').value,ship=d==='pickup'?0:(subtotal>=99?0:5.90);shipEl.textContent=ship?money(ship):'GRATIS';totalEl.textContent=money(subtotal+ship);document.getElementById('addressFields').style.display=d==='pickup'?'none':'grid';const store=document.querySelector('input[value=store]');if(store){store.disabled=d!=='pickup';if(d!=='pickup'&&store.checked)document.querySelector('input[value=card]').checked=true}}
 document.querySelectorAll('input[name=delivery]').forEach(x=>x.onchange=refresh);refresh();
 document.getElementById('checkoutForm').onsubmit=e=>{e.preventDefault();const f=e.currentTarget,err=document.getElementById('checkoutError');if(!f.checkValidity()){f.reportValidity();return}const d=f.delivery.value,pay=f.payment.value;if(pay==='store'&&d!=='pickup'){err.textContent='Il pagamento al ritiro richiede il ritiro in store.';return}const latest=inventory.products;for(const item of normalized){const p=latest.find(x=>x.id===item.id);if(!p||sizeStock(p,item.size)<item.qty){err.textContent='La disponibilità è cambiata. Torna al carrello e aggiorna l’ordine.';return}}
 const ship=d==='pickup'?0:(subtotal>=99?0:5.90),order={id:'FLP-'+Date.now().toString(36).toUpperCase(),createdAt:new Date().toISOString(),customer:Object.fromEntries(new FormData(f)),items:normalized,subtotal,shipping:ship,total:subtotal+ship,status:pay==='store'?'pending_store_payment':'pending_payment'};localStorage.setItem('flipco_last_order',JSON.stringify(order));localStorage.removeItem(CART_KEY);location.href='order-confirmation.html'};
}
document.addEventListener('DOMContentLoaded',initCheckout);
