(()=>{
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(n);
const getCart=()=>JSON.parse(localStorage.getItem('flipco-cart')||'[]');
let cart=getCart();
let products=[];
const save=()=>{localStorage.setItem('flipco-cart',JSON.stringify(cart));updateCount()};
const updateCount=()=>document.querySelectorAll('#cartCount').forEach(e=>e.textContent=cart.reduce((a,x)=>a+x.qty,0));
const stock=(p,size)=>Number(p?.stock?.[size]||0);
function add(p,size){
 const available=stock(p,size), key=p.id+'-'+size, found=cart.find(x=>x.key===key);
 const qty=found?.qty||0;
 if(!available || qty>=available) return;
 if(found) found.qty++; else cart.push({key,id:p.id,size,qty:1});
 save(); openCart();
}
function openCart(){const d=$('#cartDrawer');if(!d)return;d.classList.add('open');$('#cartBackdrop')?.classList.add('open');d.setAttribute('aria-hidden','false');renderCart()}
function closeCart(){const d=$('#cartDrawer');if(!d)return;d.classList.remove('open');$('#cartBackdrop')?.classList.remove('open');d.setAttribute('aria-hidden','true')}
function renderCart(){const box=$('#cartItems');if(!box)return;let total=0;box.innerHTML='';if(!cart.length){box.innerHTML='<div class="empty">IL TUO CARRELLO È VUOTO.<br><a href="shop.html">SCOPRI LA SELEZIONE →</a></div>'}else cart.forEach((x,i)=>{const p=products.find(p=>p.id===x.id);if(!p)return;const max=stock(p,x.size);const qty=Math.min(x.qty,max);if(qty!==x.qty)x.qty=qty;total+=p.price*qty;const el=document.createElement('article');el.className='cart-line';el.innerHTML=`<img src="${p.image}" alt="${p.brand} ${p.name}"><div><b>${p.brand}</b><span>${p.name} · ${x.size}</span><small>${qty} × ${money(p.price)}</small></div><button type="button" aria-label="Rimuovi ${p.name}" data-remove="${i}">×</button>`;box.appendChild(el)});$('#cartTotal')&&( $('#cartTotal').textContent=money(total));box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);save();renderCart()});save()}
function initShop(){const grid=$('#shopGrid'),brand=$('#brandFilter');if(!grid)return;[...new Set(products.map(p=>p.brand))].sort().forEach(b=>brand?.insertAdjacentHTML('beforeend',`<option value="${b}">${b}</option>`));let cat=new URLSearchParams(location.search).get('category')||'TUTTI';let selectedBrand=new URLSearchParams(location.search).get('brand')||'TUTTI';if(!['Uomo','Donna','Kids'].includes(cat))cat='TUTTI';if(brand)brand.value=selectedBrand;document.querySelectorAll('.chip').forEach(b=>{b.classList.toggle('active',b.dataset.cat===cat)});function render(){const bf=brand?.value||'TUTTI';const list=products.filter(p=>(cat==='TUTTI'||p.category===cat)&&(bf==='TUTTI'||p.brand===bf));grid.innerHTML=list.map(p=>{const available=Object.values(p.stock).reduce((a,b)=>a+Number(b),0);return `<article class="product-card"><a href="product.html?id=${encodeURIComponent(p.id)}" class="product-image"><img src="${p.image}" alt="${p.brand} ${p.name}" loading="lazy"><span>${p.badge||'FLIP&CO'}</span></a><div class="product-meta"><div><b>${p.brand}</b><a href="product.html?id=${encodeURIComponent(p.id)}">${p.name}</a></div><strong>${money(p.price)}</strong></div><small>${available?`DISPONIBILE · ${available} ${available===1?'PEZZO':'PEZZI'}`:'ESAURITO'}</small></article>`}).join('')||'<p class="empty">NESSUN PRODOTTO CON QUESTI FILTRI.</p>'}document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelector('.chip.active')?.classList.remove('active');b.classList.add('active');cat=b.dataset.cat;render()});brand?.addEventListener('change',render);render();$('#cartTrigger')?.addEventListener('click',e=>{e.preventDefault();openCart()});$('#cartClose')?.addEventListener('click',closeCart);$('#cartBackdrop')?.addEventListener('click',closeCart);$('#checkoutBtn')?.addEventListener('click',()=>{if(cart.length)location.href='checkout.html'});renderCart()}
function initProduct(){const root=$('#productPage');if(!root)return;const id=new URLSearchParams(location.search).get('id')||products[0]?.id,p=products.find(x=>x.id===id)||products[0];if(!p)return;document.title=`${p.name} — ${p.brand} | Flip&Co`;const total=Object.values(p.stock).reduce((a,b)=>a+Number(b),0);root.innerHTML=`<section class="product-detail"><div class="product-detail-image"><img src="${p.image}" alt="${p.brand} ${p.name}"></div><div class="product-detail-copy"><span class="micro">${p.brand}</span><h1>${p.name}</h1><div class="price">${money(p.price)}</div><p>Una selezione Flip&Co pensata per essere indossata, provata e vissuta. La disponibilità riflette lo stock associato al negozio.</p><div class="stock-state">${total?'● DISPONIBILE':'○ ESAURITO'} <span>· CAGLIARI STORE</span></div><div class="size-label">SCEGLI LA TAGLIA</div><div class="sizes">${p.sizes.map(s=>`<button type="button" data-size="${s}" ${stock(p,s)?'':'disabled'}>${s}</button>`).join('')}</div><button class="primary" id="addProduct" ${total?'':'disabled'}>AGGIUNGI AL CARRELLO</button><div class="store-bridge"><b>VUOI VEDERLO DAL VIVO?</b><p>Se disponibile, puoi venire a provarlo in negozio. Per verificare una taglia prima di partire, scrivici su WhatsApp.</p><a href="index.html#store">VIENI IN STORE ↗</a><a target="_blank" rel="noopener" href="https://wa.me/393661087819?text=${encodeURIComponent('Ciao Flip&Co, vorrei verificare la disponibilità di '+p.brand+' '+p.name)}">WHATSAPP ↗</a></div></div></section>`;let selected=null;root.querySelectorAll('.sizes button').forEach(b=>b.onclick=()=>{root.querySelector('.sizes .selected')?.classList.remove('selected');b.classList.add('selected');selected=b.dataset.size});$('#addProduct')?.addEventListener('click',()=>selected&&add(p,selected));updateCount()}
function initCheckout(){const f=$('#checkoutForm');if(!f)return;const items=cart.map(x=>{const p=products.find(p=>p.id===x.id);return p?`${p.brand} ${p.name} — ${x.size} × ${x.qty}`:''}).filter(Boolean);$('#checkoutSummary')&&($('#checkoutSummary').textContent=items.length?items.join(' | '):'Il carrello è vuoto.');f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f);const name=fd.get('name');const msg=`Ciao Flip&Co, vorrei ordinare:%0A${encodeURIComponent(items.join('\n'))}%0A%0ANome: ${encodeURIComponent(name)}%0AEmail: ${encodeURIComponent(fd.get('email'))}%0ATelefono: ${encodeURIComponent(fd.get('phone'))}%0AIndirizzo: ${encodeURIComponent(fd.get('address'))}%0ANote: ${encodeURIComponent(fd.get('notes')||'')}`;$('#checkoutResult').hidden=false;$('#checkoutResult').innerHTML=`<b>Richiesta pronta.</b><br>Per completare l'ordine, inviala a Flip&Co via WhatsApp. Ti confermeremo disponibilità, spedizione e pagamento.`;localStorage.removeItem('flipco-cart');cart=[];save();setTimeout(()=>location.href='https://wa.me/393661087819?text='+msg,250)}}
fetch('products.json').then(r=>r.json()).then(ps=>{products=ps;updateCount();initShop();initProduct();initCheckout()}).catch(()=>{document.body.insertAdjacentHTML('beforeend','<p class="load-error">Impossibile caricare la selezione. Riprova tra poco.</p>')});
})();