const CART_KEY='flipco_cart_v5';
function getCart(){try{return JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{return[]}}
function saveCart(cart){localStorage.setItem(CART_KEY,JSON.stringify(cart));updateCartCount();window.dispatchEvent(new Event('cartupdated'))}
function updateCartCount(){const n=getCart().reduce((s,i)=>s+Number(i.qty||0),0);document.querySelectorAll('#cartCount').forEach(e=>e.textContent=n)}
function cartTotal(){return getCart().reduce((s,i)=>s+Number(i.price||0)*Number(i.qty||0),0)}
function addToCart(p,size,qty=1){const available=sizeStock(p,size);if(!available)return{ok:false,message:'Questa taglia non è più disponibile.'};const cart=getCart(),key=p.id+'__'+size,found=cart.find(i=>i.key===key),current=found?Number(found.qty):0;if(current+qty>available)return{ok:false,message:`Disponibilità massima: ${available}.`};if(found)found.qty+=qty;else cart.push({key,id:p.id,brand:p.brand,name:p.name,size,price:p.price,qty,image:p.image,category:p.category});saveCart(cart);return{ok:true}}
function removeFromCart(key){saveCart(getCart().filter(i=>i.key!==key));renderCart?.()}
function changeQty(key,delta){const cart=getCart(),item=cart.find(i=>i.key===key);if(!item)return;const p=productById(item.id);if(!p)return removeFromCart(key);const next=Number(item.qty)+delta;if(next<1)return removeFromCart(key);const max=sizeStock(p,item.size);if(next>max){showCartNotice?.(`Disponibilità massima per la taglia ${item.size}: ${max}.`);return}item.qty=next;saveCart(cart);renderCart?.()}
function showCartNotice(msg){const el=document.getElementById('cartNotice');if(!el)return;el.textContent=msg;el.hidden=false;clearTimeout(window.__flipNotice);window.__flipNotice=setTimeout(()=>el.hidden=true,2800)}
function renderCart(){const box=document.getElementById('cartItems'),total=document.getElementById('cartTotal');if(!box)return;const cart=getCart();box.innerHTML=cart.length?cart.map(i=>`<article class="cart-item"><img src="${escapeHtml(i.image)}" alt="${escapeHtml(i.brand)} ${escapeHtml(i.name)}"><div class="cart-item-copy"><span>${escapeHtml(i.brand)}</span><strong>${escapeHtml(i.name)}</strong><small>Taglia ${escapeHtml(i.size)}</small><div class="qty"><button data-q="${escapeHtml(i.key)}" data-d="-1" aria-label="Diminuisci">−</button><b>${i.qty}</b><button data-q="${escapeHtml(i.key)}" data-d="1" aria-label="Aumenta">+</button><button class="remove" data-r="${escapeHtml(i.key)}">RIMUOVI</button></div></div><b class="cart-item-price">${money(i.price*i.qty)}</b></article>`).join(''):`<div class="cart-empty"><span>IL TUO BAG È VUOTO.</span><strong>SCOPRI LA SELEZIONE.</strong><a href="shop.html">SHOP ONLINE →</a></div>`;if(total)total.textContent=money(cartTotal());box.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>changeQty(b.dataset.q,Number(b.dataset.d)));box.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>removeFromCart(b.dataset.r))}
function setupCartDrawer(){updateCartCount();const drawer=document.getElementById('cartDrawer'),back=document.getElementById('cartBackdrop'),trigger=document.getElementById('cartTrigger'),closeBtn=document.getElementById('cartClose');if(!drawer)return;const open=()=>{drawer.classList.add('open');back?.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.classList.add('cart-open');renderCart();closeBtn?.focus()};const close=()=>{drawer.classList.remove('open');back?.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.classList.remove('cart-open');trigger?.focus()};trigger?.addEventListener('click',e=>{e.preventDefault();open()});closeBtn?.addEventListener('click',close);back?.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drawer.classList.contains('open'))close()});window.addEventListener('cartupdated',()=>{updateCartCount();if(drawer.classList.contains('open'))renderCart()});if(location.hash==='#cart')setTimeout(open,100)}
document.addEventListener('DOMContentLoaded',setupCartDrawer);
