(()=>{
const mount=document.getElementById('productStoryMount');if(!mount)return;
const esc=window.escapeHtml||((v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])));
const money=window.money||((v)=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v)||0));
let products=[];
async function init(){try{const d=await loadInventory();products=d.products||[]}catch{mount.innerHTML='<div class="home-error">CATALOGO NON DISPONIBILE.</div>';return}render();}
function images(p){return Array.isArray(p.images)&&p.images.length?p.images:[p.image].filter(Boolean)}
function render(){const list=products.filter(p=>stockFor(p)>0).slice(0,12);mount.innerHTML=list.map((p,i)=>{const im=images(p)[0];return `<article class="product-story" data-id="${esc(p.id)}"><a class="story-media" href="product.html?id=${encodeURIComponent(p.id)}" aria-label="Apri ${esc(p.name)}"><span class="story-index">${String(i+1).padStart(2,'0')} / ${String(list.length).padStart(2,'0')}</span><img src="${esc(im)}" alt="${esc(p.brand)} ${esc(p.name)}" loading="${i<2?'eager':'lazy'}"></a><div class="story-info"><div class="story-top"><p class="story-brand">${esc(p.brand)}</p><h2 class="story-name">${esc(p.name)}</h2><p class="story-price">${money(p.price)}</p></div><div class="story-bottom"><div class="story-meta"><span>${esc(p.category)}</span><span>${stockFor(p)} ${stockFor(p)===1?'PEZZO':'PEZZI'} · DISPONIBILE</span></div><div class="size-row">${(p.sizes||[]).map(s=>`<button class="size-btn" type="button" data-size="${esc(s)}" ${sizeStock(p,s)?'':'disabled'}>${esc(s)}</button>`).join('')}</div><button class="add-btn" type="button" data-add="${esc(p.id)}">SELEZIONA UNA TAGLIA</button><a class="detail-link" href="product.html?id=${encodeURIComponent(p.id)}">VEDI DETTAGLI ↗</a></div></div></article>`}).join('');
mount.querySelectorAll('.size-row').forEach(row=>row.addEventListener('click',e=>{const b=e.target.closest('.size-btn');if(!b||b.disabled)return;row.querySelectorAll('.size-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const add=row.closest('.story-info').querySelector('[data-add]');add.dataset.size=b.dataset.size;add.textContent='AGGIUNGI AL BAG'}));
mount.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>{if(!b.dataset.size){b.closest('.story-info').querySelector('.size-btn:not(:disabled)')?.click();return}const p=products.find(x=>x.id===b.dataset.add);const r=addToCart(p,b.dataset.size);if(!r.ok){showCartNotice?.(r.message);return}b.textContent='AGGIUNTO ✓';document.getElementById('cartTrigger')?.click();setTimeout(()=>b.textContent='AGGIUNGI AL BAG',1300)}));}
init();})();