(()=>{
const CART_KEY='flipco_cart_v5';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v)||0);
function count(){let c=[];try{c=JSON.parse(localStorage.getItem(CART_KEY)||'[]')}catch{};const n=c.reduce((a,x)=>a+Number(x.qty||0),0);document.querySelectorAll('#cartCount').forEach(x=>x.textContent=n)}
function markup(){return `<div class="menu-shell" role="dialog" aria-modal="true" aria-label="Menu principale"><div class="menu-top"><span class="eyebrow">FLIP&CO · CAGLIARI</span><button class="menu-close" type="button">CHIUDI ×</button></div><div class="menu-grid"><nav class="menu-main"><a href="index.html">HOME <i>01</i></a><a href="shop.html">SHOP <i>02</i></a><a href="shop.html?category=Uomo">UOMO <i>03</i></a><a href="shop.html?category=Donna">DONNA <i>04</i></a><a href="shop.html?category=Kids">KIDS <i>05</i></a><a href="brand.html">BRAND <i>06</i></a><a href="index.html#store">STORE <i>07</i></a></nav><aside class="menu-side"><span class="eyebrow">FLIP&CO / STORE</span><strong>VIA ITALIA 22<br>CAGLIARI</strong><small>LUN—SAB<br>09:00—13:30<br>16:00—20:00</small><a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=Via+Italia+22%2C+Cagliari">COME ARRIVARE ↗</a><a target="_blank" rel="noopener" href="https://www.instagram.com/flipabbigliamento/">INSTAGRAM ↗</a></aside></div></div>`}
function setup(){
 const h=document.querySelector('.site-header'); if(!h)return;
 const btn=h.querySelector('#menuBtn,.menu-button,.v18-mobile-menu'); if(!btn)return;
 const oldLegacy=h.querySelector('#legacyMenuBtn'); if(oldLegacy) oldLegacy.remove();
 let overlay=document.getElementById('mobileMenu'); if(!overlay){overlay=document.createElement('div');overlay.id='mobileMenu';overlay.className='menu-overlay';overlay.setAttribute('aria-hidden','true');overlay.innerHTML=markup();document.body.appendChild(overlay)}
 const open=()=>{overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');btn.setAttribute('aria-expanded','true');document.body.classList.add('menu-open');overlay.querySelector('.menu-close')?.focus()};
 const close=()=>{overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true');btn.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')};
 btn.addEventListener('click',e=>{e.preventDefault();overlay.classList.contains('open')?close():open()});overlay.querySelector('.menu-close').onclick=close;overlay.querySelectorAll('a').forEach(a=>a.onclick=close);
 let search=h.querySelector('.header-search'); if(search){let so=document.getElementById('searchOverlay');if(!so){so=document.createElement('div');so.id='searchOverlay';so.className='search-overlay';so.innerHTML='<div class="search-shell"><div class="search-head"><span class="eyebrow">FLIP&CO / CERCA</span><button class="search-close" type="button">CHIUDI ×</button></div><input id="siteSearch" type="search" placeholder="Brand, prodotto, categoria…" aria-label="Cerca nel catalogo"><div id="searchResults"></div></div>';document.body.appendChild(so)}const input=so.querySelector('#siteSearch'),results=so.querySelector('#searchResults');const closeSearch=()=>{so.classList.remove('open');so.setAttribute('aria-hidden','true');document.body.classList.remove('search-open')};search.addEventListener('click',()=>{so.classList.add('open');so.setAttribute('aria-hidden','false');document.body.classList.add('search-open');setTimeout(()=>input.focus(),120)});so.querySelector('.search-close').onclick=closeSearch;input.addEventListener('input',async()=>{const q=input.value.trim().toLowerCase();if(!q){results.innerHTML='';return}try{const d=await (await fetch('inventory/inventory.json',{cache:'no-store'})).json();const hits=(d.products||[]).filter(p=>`${p.brand} ${p.name} ${p.category} ${p.season}`.toLowerCase().includes(q)).slice(0,10);results.innerHTML=hits.map(p=>`<a class="search-result" href="product.html?id=${encodeURIComponent(p.id)}"><span>${esc(p.brand)} — ${esc(p.name)}</span><span>${money(p.price)}</span></a>`).join('')||'<p>Nessun risultato.</p>'}catch{results.innerHTML='<p>Catalogo non disponibile.</p>'}})}
 const cart=h.querySelector('#cartTrigger'); if(cart&&!cart.dataset.navbound){cart.dataset.navbound='1';cart.addEventListener('click',e=>{if(document.getElementById('cartDrawer')){e.preventDefault();document.getElementById('cartDrawer').classList.add('open');document.getElementById('cartBackdrop')?.classList.add('open');document.body.classList.add('cart-open');document.getElementById('cartDrawer').setAttribute('aria-hidden','false');renderCart?.()}})}
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){close();document.getElementById('searchOverlay')?.classList.remove('open');document.body.classList.remove('search-open')}});window.addEventListener('storage',count);window.addEventListener('cartupdated',count);count();
}
document.addEventListener('DOMContentLoaded',setup);
})();