async function initProduct(){
 const id=new URLSearchParams(location.search).get('id'),data=await loadInventory().catch(()=>null),p=data?.products?.find(x=>x.id===id),root=document.getElementById('productView');
 if(!p){root.innerHTML='<div class="not-found"><h1>PRODOTTO NON TROVATO.</h1><a class="text-link" href="shop.html">TORNA ALLO SHOP →</a></div>';return}
 document.title=`${p.name} — ${p.brand} | Flip&Co`;
 const total=stockFor(p);
 root.innerHTML=`<div class="product-gallery"><div class="gallery-main"><img src="${escapeHtml(p.image)}" alt="${escapeHtml(p.brand)} ${escapeHtml(p.name)}" fetchpriority="high" onerror="this.src='assets/editorial-campaign.jpg'"></div><div class="gallery-caption">${escapeHtml(p.brand.toUpperCase())} / ${escapeHtml(p.season)} / FLIP&CO</div></div><section class="product-detail"><a class="back-link" href="shop.html">← TORNA ALLO SHOP</a><span class="eyebrow">${escapeHtml(p.category)} / ${escapeHtml(p.brand)} / ${escapeHtml(p.badge||'SELECTION')}</span><h1>${escapeHtml(p.name)}</h1><strong class="product-price">${money(p.price)}</strong><p class="product-description">Selezione Flip&Co della stagione ${escapeHtml(p.season)}. La disponibilità online viene alimentata dall'inventario unico del negozio.</p><div class="stock-state ${total?'in':'out'}">${total?'● DISPONIBILE · '+total+' '+(total===1?'PEZZO':'PEZZI'):'● NON DISPONIBILE'}</div><div class="size-block"><div class="size-heading"><span class="label">SCEGLI LA TAGLIA</span><span class="size-note">Disponibilità reale Flip&Co</span></div><div class="sizes">${p.sizes.map(s=>`<button type="button" class="size ${p.stock[s]?'':'disabled'}" ${p.stock[s]?'':'disabled'} data-size="${escapeHtml(s)}">${escapeHtml(s)}</button>`).join('')}</div></div><div class="purchase-box"><button class="btn btn-primary full" id="addBtn" disabled>AGGIUNGI AL CARRELLO</button><p id="addMessage" aria-live="polite">Seleziona una taglia per continuare.</p></div><div class="delivery-options"><article><b>SPEDIZIONE</b><span>€ 5,90 · gratuita da € 99.</span></article><article><b>RITIRO IN STORE</b><span>Via Italia 22, Cagliari · gratuito.</span></article></div><a class="store-link" target="_blank" rel="noopener" href="https://wa.me/393661087819?text=${encodeURIComponent('Ciao Flip&Co, vorrei sapere se '+p.brand+' '+p.name+' è disponibile in negozio.')}" ><strong>VUOI VEDERLO DAL VIVO?</strong><span>Scrivici su WhatsApp o vieni in Via Italia 22.</span>WHATSAPP ↗</a><details class="product-details" open><summary>DETTAGLI PRODOTTO</summary><div class="details"><div><span>COLORE</span><b>${escapeHtml(p.color)}</b></div><div><span>MATERIALE</span><b>${escapeHtml(p.material)}</b></div><div><span>VESTIBILITÀ</span><b>${escapeHtml(p.fit)}</b></div></div></details><div class="product-assurance"><b>UN SOLO STOCK</b><span>Lo stesso inventario alimenta store fisico e shop online.</span></div></section>`;
 let selected=null;
 root.querySelectorAll('.size:not(.disabled)').forEach(b=>b.onclick=()=>{root.querySelectorAll('.size').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=b.dataset.size;document.getElementById('addBtn').disabled=false;document.getElementById('addMessage').textContent=`Taglia ${selected} selezionata.`});
 document.getElementById('addBtn').onclick=()=>{const r=addToCart(p,selected);const m=document.getElementById('addMessage');if(!r.ok){m.textContent=r.message;return}document.getElementById('addBtn').textContent='AGGIUNTO AL CARRELLO ✓';m.textContent='Prodotto aggiunto. Apertura carrello…';setTimeout(()=>location.href='shop.html#cart',400)};
}
document.addEventListener('DOMContentLoaded',initProduct);
