let SHOP_PRODUCTS=[];
const params=new URLSearchParams(location.search);
const shopState={cat:params.get('category')||'TUTTI',brand:params.get('brand')||'TUTTI',size:'TUTTE',sort:'featured',stockOnly:false,cols:2};
const $=s=>document.querySelector(s);
async function initShop(){
  const data=await loadInventory().catch(()=>null); SHOP_PRODUCTS=data?.products||[];
  if(!SHOP_PRODUCTS.length){$('#shopGrid').innerHTML='<div class="shop-empty"><strong>CATALOGO NON DISPONIBILE.</strong></div>';return}
  const brands=[...new Set(SHOP_PRODUCTS.map(p=>p.brand))].sort();
  const sizes=[...new Set(SHOP_PRODUCTS.flatMap(p=>p.sizes||[]))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));
  fillSelect($('#brandFilterMobile'),brands,'TUTTI'); fillSelect($('#sizeFilterMobile'),sizes,'TUTTE'); $('#catFilterMobile').value=shopState.cat;
  document.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>{shopState.cat=b.dataset.cat;$('#catFilterMobile').value=shopState.cat;syncCategories();renderShop();scrollToGrid()}));
  $('#sortFilter').value=shopState.sort; $('#sortFilter').addEventListener('change',e=>{shopState.sort=e.target.value;renderShop()});
  $('#stockToggle')?.addEventListener('click',e=>{shopState.stockOnly=!shopState.stockOnly;e.currentTarget.setAttribute('aria-pressed',shopState.stockOnly);renderShop()});
  $('#filterOpen')?.addEventListener('click',()=>$('#filterSheet')?.classList.add('open'));
  $('#filterClose')?.addEventListener('click',()=>$('#filterSheet')?.classList.remove('open'));
  $('#filterApply')?.addEventListener('click',()=>{shopState.cat=$('#catFilterMobile').value;shopState.brand=$('#brandFilterMobile').value;shopState.size=$('#sizeFilterMobile').value;syncCategories();renderShop();$('#filterSheet').classList.remove('open')});
  $('#filterSheet')?.addEventListener('click',e=>{if(e.target.id==='filterSheet')e.currentTarget.classList.remove('open')});
  $('#viewToggle')?.addEventListener('click',()=>{shopState.cols=shopState.cols===2?1:2;$('#shopGrid').classList.toggle('one-col',shopState.cols===1);$('#viewToggle span').textContent=shopState.cols;});
  syncCategories();renderShop();
}
function fillSelect(el,values,first){if(!el)return;el.innerHTML=`<option value="${first}">${first}</option>`+values.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');}
function syncCategories(){document.querySelectorAll('[data-cat]').forEach(b=>b.classList.toggle('active',b.dataset.cat===shopState.cat));}
function scrollToGrid(){requestAnimationFrame(()=>$('#shopGrid')?.scrollIntoView({behavior:'smooth',block:'start'}))}
function productCard(p,i){const available=stockFor(p);return `<article class="z-product-card v18-card"><a href="product.html?id=${encodeURIComponent(p.id)}" class="z-product-link"><div class="z-product-media"><img src="${escapeHtml(p.image)}" alt="${escapeHtml(p.brand)} ${escapeHtml(p.name)}" loading="${i<4?'eager':'lazy'}"><button class="v18-wish" type="button" data-wish="${escapeHtml(p.id)}" aria-label="Salva prodotto">♡</button>${p.badge?`<span class="v18-badge">${escapeHtml(p.badge)}</span>`:''}<button class="z-quick-add v18-quick-trigger" type="button" data-quick="${escapeHtml(p.id)}" aria-label="Scegli la taglia">+</button><span class="v18-card-add">AGGIUNGI</span></div><div class="z-product-meta"><span>${escapeHtml(p.brand)}</span><h2>${escapeHtml(p.name)}</h2><b>${money(p.price)}</b><small>${available?`Disponibile · ${available}`:'Esaurito'}</small></div></a></article>`}
function renderShop(){let list=SHOP_PRODUCTS.filter(p=>(shopState.cat==='TUTTI'||p.category===shopState.cat)&&(shopState.brand==='TUTTI'||p.brand===shopState.brand)&&(shopState.size==='TUTTE'||sizeStock(p,shopState.size)>0)&&(!shopState.stockOnly||stockFor(p)>0));if(shopState.sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(shopState.sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(shopState.sort==='new')list.sort((a,b)=>String(b.badge).localeCompare(String(a.badge)));$('#resultCount').textContent=`${list.length} ${list.length===1?'PRODOTTO':'PRODOTTI'}`;$('#shopGrid').innerHTML=list.map(productCard).join('')||'<div class="shop-empty"><strong>NESSUN RISULTATO.</strong><span>Modifica i filtri per continuare.</span></div>';wireCards();}
function wireCards(){document.querySelectorAll('[data-quick]').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openQuickAdd(btn.dataset.quick)}));document.querySelectorAll('[data-wish]').forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();toggleWish(btn)}));}
function toggleWish(btn){const key='flipco_wishlist';let a=[];try{a=JSON.parse(localStorage.getItem(key)||'[]')}catch{}const id=btn.dataset.wish;const has=a.includes(id);a=has?a.filter(x=>x!==id):[...a,id];localStorage.setItem(key,JSON.stringify(a));btn.classList.toggle('saved',!has);btn.textContent=has?'♡':'♥';}
function openQuickAdd(id){const p=SHOP_PRODUCTS.find(x=>x.id===id);if(!p)return;const sheet=$('#quickSheet');sheet.querySelector('.quick-brand').textContent=p.brand;sheet.querySelector('.quick-name').textContent=p.name;sheet.querySelector('.quick-price').textContent=money(p.price);sheet.querySelector('.quick-image').src=p.image;sheet.querySelector('.quick-view-product').href=`product.html?id=${encodeURIComponent(p.id)}`;sheet.querySelector('.quick-sizes').innerHTML=(p.sizes||[]).map(s=>`<button type="button" class="quick-size ${sizeStock(p,s)?'':'disabled'}" ${sizeStock(p,s)?'':'disabled'} data-size="${escapeHtml(s)}">${escapeHtml(s)}</button>`).join('');sheet.dataset.id=id;sheet.classList.add('open');document.body.classList.add('sheet-open');const confirm=sheet.querySelector('.quick-add-confirm');confirm.disabled=true;sheet.querySelectorAll('.quick-size:not(.disabled)').forEach(b=>b.onclick=()=>{sheet.querySelectorAll('.quick-size').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');sheet.dataset.size=b.dataset.size;confirm.disabled=false});}
document.addEventListener('DOMContentLoaded',()=>{initShop().then(()=>{const s=$('#quickSheet');s?.querySelector('.quick-close')?.addEventListener('click',()=>{s.classList.remove('open');document.body.classList.remove('sheet-open')});s?.querySelector('.quick-add-confirm')?.addEventListener('click',()=>{const p=SHOP_PRODUCTS.find(x=>x.id===s.dataset.id),r=addToCart(p,s.dataset.size);if(r.ok){s.classList.remove('open');document.body.classList.remove('sheet-open');$('#cartTrigger')?.click()}else showCartNotice(r.message)});});});
